### PR TITLE
Add export order for TIMES entities

### PR DESCRIPTION
**Pull request by olejandro**
This PR categorises TIMES entities into the following categories: `set`, `subset`, `subsubset`, `md-set`, and `parameter` and makes the tool export them in this order.

### CODE REVIEW

**Comment by olejandro** [comment]
@siddharth-krishna, I've added `times-info.json` to this branch. Do you have enough info to be able to use it for the printing order in dd files?

**Comment by siddharth-krishna** [comment]
@olejandro thanks, this should be just what I need! I'll work on modifying the DD output routine.

A thought: should we try to merge this information and the information in `times_mapping.txt` into one nicely structured YAML/JSON file?

**Comment by olejandro** [comment]
Good point! Let's discuss a possible approach soon. :-)

**Comment by siddharth-krishna** [comment]
I modified the code to use the category order from `times-info.json`, but now GAMS errors on all Demos, including Demo 1 which used to work earlier. A snippet from its output:
```
*** Error 170 in /home/runner/work/times-excel-reader/times-excel-reader/times-excel-reader/benchmarks/out/DemoS_001-all/output.dd
    Domain violation for element
--- . output.dd(65) 3 Mb 2 Errors
*** Error 170 in /home/runner/work/times-excel-reader/times-excel-reader/times-excel-reader/benchmarks/out/DemoS_001-all/output.dd
    Domain violation for element
--- . output.dd(66) 3 Mb 3 Errors
*** Error 170 in /home/runner/work/times-excel-reader/times-excel-reader/times-excel-reader/benchmarks/out/DemoS_001-all/output.dd
    Domain violation for element
--- . output.dd(67) 3 Mb 4 Errors
*** Error 170 in /home/runner/work/times-excel-reader/times-excel-reader/times-excel-reader/benchmarks/out/DemoS_001-all/output.dd
    Domain violation for element
--- . output.dd(68) 3 Mb 5 Errors
*** Error 170 in /home/runner/work/times-excel-reader/times-excel-reader/times-excel-reader/benchmarks/out/DemoS_001-all/output.dd
    Domain violation for element
--- . output.dd(69) 3 Mb 6 Errors
*** Error 170 in /home/runner/work/times-excel-reader/times-excel-reader/times-excel-reader/benchmarks/out/DemoS_001-all/output.dd
    Domain violation for element
--- . output.dd(74) 3 Mb 7 Errors
*** Error 170 in /home/runner/work/times-excel-reader/times-excel-reader/times-excel-reader/benchmarks/out/DemoS_001-all/output.dd
    Domain violation for element
--- . output.dd(75) 3 Mb 8 Errors
```

Here's the table order as computed from categories (and alphabetical within categories) in case I'm missing something obvious:

> table_order = ['ALL_REG', 'ALL_TS', 'COM_GRP', 'CUR', 'PRC', 'SPE', 'UC_N', 'UNITS', 'COM', 'MILESTONYR', 'UNITS_ACT', 'UNITS_CAP', 'UNITS_COM', 'BLE', 'OPR', 'ACT_BND', 'ACT_COST', 'ACT_CSTPL', 'ACT_CSTRMP', 'ACT_CSTSD', 'ACT_CSTUP', 'ACT_CUM', 'ACT_EFF', 'ACT_FLO', 'ACT_LOSPL', 'ACT_LOSSD', 'ACT_MAXNON', 'ACT_MINLD', 'ACT_SDTIME', 'ACT_TIME', 'ACT_UPS', 'B', 'BL_COM', 'BL_DELIVC', 'BL_INP', 'BL_SPEC', 'BL_START', 'BL_TYPE', 'BL_UNIT', 'BL_VAROMC', 'BS_BNDPRS', 'BS_CAPACT', 'BS_DELTA', 'BS_DEMDET', 'BS_DETWT', 'BS_LAMBDA', 'BS_MAINT', 'BS_OMEGA', 'BS_RMAX', 'BS_RTYPE', 'BS_SHARE', 'BS_SIGMA', 'BS_STIME', 'CAP_BND', 'CM_CO2GTC', 'CM_CONST', 'CM_EXOFORC', 'CM_GHGMAP', 'CM_HISTORY', 'CM_LINFOR', 'CM_MAXC', 'CM_MAXCO2C', 'CM_PPM', 'COM_AGG', 'COM_BNDNET', 'COM_BNDPRD', 'COM_BPRICE', 'COM_BQTY', 'COM_CSTBAL', 'COM_CSTNET', 'COM_CSTPRD', 'COM_CUMNET', 'COM_CUMPRD', 'COM_ELAST', 'COM_ELASTX', 'COM_FR', 'COM_IE', 'COM_MSHGV', 'COM_PKFLX', 'COM_PKRSV', 'COM_PROJ', 'COM_STEP', 'COM_SUBNET', 'COM_SUBPRD', 'COM_TAXNET', 'COM_TAXPRD', 'COM_VOC', 'CONVERT', 'DAM_BQTY', 'DAM_COST', 'DAM_ELAST', 'DAM_STEP', 'DAM_TQTY', 'DAM_TVOC', 'DAM_VOC', 'E', 'ENV_BL', 'FLO_BND', 'FLO_COST', 'FLO_CUM', 'FLO_DELIV', 'FLO_EFF', 'FLO_EMIS', 'FLO_FEQ', 'FLO_FR', 'FLO_FUNC', 'FLO_FUNCX', 'FLO_MARK', 'FLO_PKCOI', 'FLO_SHAR', 'FLO_SUB', 'FLO_SUM', 'FLO_TAX', 'GR_DEMFR', 'GR_ENDFR', 'GR_GENFR', 'GR_GENLEV', 'GR_GENMAP', 'GR_THMIN', 'GR_VARGEN', 'GR_XBND', 'G_CUREX', 'G_CYCLE', 'G_DRATE', 'G_DYEAR', 'G_ILEDNO', 'G_OFFTHD', 'G_OVERLAP', 'G_RFRIR', 'G_TLIFE', 'G_YRFR', 'IRE_BND', 'IRE_CCVT', 'IRE_FLO', 'IRE_FLOSUM', 'IRE_PRICE', 'IRE_TSCVT', 'IRE_XBND', 'MULTI', 'NCAP_AF', 'NCAP_AFA', 'NCAP_AFAC', 'NCAP_AFC', 'NCAP_AFCS', 'NCAP_AFM', 'NCAP_AFS', 'NCAP_AFSX', 'NCAP_AFX', 'NCAP_BND', 'NCAP_BPME', 'NCAP_CDME', 'NCAP_CEH', 'NCAP_CHPR', 'NCAP_CLAG', 'NCAP_CLED', 'NCAP_COM', 'NCAP_COST', 'NCAP_CPX', 'NCAP_DCOST', 'NCAP_DELIF', 'NCAP_DISC', 'NCAP_DLAG', 'NCAP_DLAGC', 'NCAP_DLIFE', 'NCAP_DRATE', 'NCAP_ELIFE', 'NCAP_FDR', 'NCAP_FOM', 'NCAP_FOMM', 'NCAP_FOMX', 'NCAP_FSUB', 'NCAP_FSUBM', 'NCAP_FSUBX', 'NCAP_FTAX', 'NCAP_FTAXM', 'NCAP_FTAXX', 'NCAP_ICOM', 'NCAP_ILED', 'NCAP_ISPCT', 'NCAP_ISUB', 'NCAP_ITAX', 'NCAP_LCOST', 'NCAP_LFOM', 'NCAP_MSPRF', 'NCAP_OCOM', 'NCAP_OLIFE', 'NCAP_PASTI', 'NCAP_PASTY', 'NCAP_PKCNT', 'NCAP_SEMI', 'NCAP_START', 'NCAP_TLIFE', 'NCAP_VALU', 'PEAKDA_BL', 'PRC_ACTFLO', 'PRC_CAPACT', 'PRC_GMAP', 'PRC_MARK', 'PRC_REACT', 'PRC_REFIT', 'PRC_RESID', 'RCAP_BLK', 'RCAP_BND', 'REFUNIT', 'REG_BDNCAP', 'REG_BNDCST', 'REG_CUMCST', 'REG_FIXT', 'RPT_OPT', 'R_CUREX', 'SHAPE', 'STGIN_BND', 'STGOUT_BND', 'STG_CHRG', 'STG_EFF', 'STG_LOSS', 'STG_MAXCYC', 'STG_SIFT', 'SW_LAMBDA', 'SW_PROB', 'SW_SPROB', 'SW_START', 'SW_SUBS', 'S_CAP_BND', 'S_CM_CONST', 'S_CM_MAXC', 'S_CM_MAXCO2C', 'S_COM_CUMNET', 'S_COM_CUMPRD', 'S_COM_FR', 'S_COM_PROJ', 'S_COM_TAX', 'S_DAM_COST', 'S_FLO_CUM', 'S_FLO_FUNC', 'S_NCAP_AFS', 'S_NCAP_COST', 'S_UCOBJ', 'S_UC_RHS', 'S_UC_RHSR', 'S_UC_RHSRT', 'S_UC_RHSRTS', 'S_UC_RHST', 'S_UC_RHSTS', 'TL_CCAP0', 'TL_CCAPM', 'TL_CLUSTER', 'TL_MRCLUST', 'TL_PRAT', 'TL_SC0', 'TL_SEG', 'TM_ARBM', 'TM_DEFVAL', 'TM_DEPR', 'TM_DESUB', 'TM_DMTOL', 'TM_ESUB', 'TM_EXPBND', 'TM_EXPF', 'TM_GDP0', 'TM_GR', 'TM_HSX', 'TM_IVETOL', 'TM_KGDP', 'TM_KPVS', 'TM_MDTL', 'TM_MDTQ', 'TM_QFAC', 'TM_SCALE_CST', 'TM_SCALE_NRG', 'TM_SCALE_UTIL', 'TM_STEP', 'TM_VOC', 'TS_CYCLE', 'UC_ACT', 'UC_ATTR', 'UC_CAP', 'UC_CLI', 'UC_COMCON', 'UC_COMNET', 'UC_COMPRD', 'UC_CUMACT', 'UC_CUMCOM', 'UC_CUMFLO', 'UC_DYNBND', 'UC_FLO', 'UC_FLOBET', 'UC_IRE', 'UC_NCAP', 'UC_RHS', 'UC_RHSR', 'UC_RHSRT', 'UC_RHSRTS', 'UC_RHST', 'UC_RHSTS', 'UC_TIME', 'UC_UCN', 'VDA_CEH', 'VDA_EMCB', 'VDA_FLOP']


Meanwhile, here's a proposal for how the combined mapping/category file could look. For the mapping `G_DRATE[REG,DATAYEAR,CUR,VALUE] = ~FI_T(Region,Year,Curr,VALUE,Attribute:G_DRATE)`, we could have the entry:
```yaml
- name: G_DRATE
  category: parameter
  times-cols:
    - REG
    - DATAYEAR
    - CUR
    - VALUE
  xl-cols:
    - Region
    - Year
    - Curr
    - VALUE
  filter-attribute: G_DRATE
```
Alternatively, in JSON format (though perhaps YAML is a bit more readable?)
```json
[
  {
    "name": "G_DRATE",
    "category": "parameter",
    "times-cols": [
      "REG",
      "DATAYEAR",
      "CUR",
      "VALUE"
    ],
    "xl-cols": [
      "Region",
      "Year",
      "Curr",
      "VALUE"
    ],
    "filter-attribute": "G_DRATE"
  }
]
```

**Comment by olejandro** [comment]
Looks like only `set` and `parameter ` categories are included, but not `subset`, `subsubset`, and `md-set`?

**Comment by siddharth-krishna** [comment]
> Looks like only set and parameter categories are included, but not subset, subsubset, and md-set?

Hmm I don't think so. The `output.dd` I generate for Demo 1 has `UNITS_ACT` for instance, which is a `subset`. I also checked that the new table order has the same 300 entities in it as the `times-info.json` file. Perhaps you are looking at the code that distinguishes between a GAMS `SET` and `PARAMETER`, which is not changed by this PR?

Here's the DD file, in case you can spot any errors:
[output.dd.txt](https://github.com/etsap-TIMES/times-excel-reader/files/12322450/output.dd.txt)

**Comment by olejandro** [comment]
Ok, thanks, will check. Maybe something is missing in the `times-info.json`, because e.g. `REG` wasn't included in the ordered list.

**Comment by olejandro** [comment]
@siddharth-krishna, it seems to be working now, but the difference between gdx files has increased... 🤔

**Comment by siddharth-krishna** [comment]
Looks like we are still missing the following entities in `times-info.json` (as compared to `times_mapping.txt`):
> ['COM_DESC', 'COM_GMAP', 'COM_LIM', 'COM_PEAK', 'COM_PKTS', 'COM_TMAP', 'COM_TSL', 'COM_UNIT', 'DATAYEAR', 'MODLYEAR', 'NRG_TMAP', 'PASTYEAR', 'PRC_ACTUNT', 'PRC_DESC', 'PRC_DSCNCAP', 'PRC_MAP', 'PRC_NOFF', 'PRC_TSL', 'PRC_VINT', 'REG', 'TOP', 'TOP_IRE', 'TS_GROUP', 'TS_MAP', 'UNITS_MONY']

Perhaps this is a benefit of having a unified file -- less likely that an entity will be in one and not another?

**Comment by olejandro** [comment]
Thanks for spotting those! Will modify the file accordingly. I don't think we should be mixing the discussion on a single file with this PR. :-) I would prefer gradually including more info in subsequent PRs instead.

**Review by siddharth-krishna — APPROVED** [review]

**Pull request merged**
