### PR TITLE
Normalize column names based on veda-tags.json

### PR DESCRIPTION
**Pull request by siddharth-krishna**

### CODE REVIEW

**Comment by olejandro** [comment]
@siddharth-krishna I had a quick look at the changes and I think I know where (part of) the problem is. In case of `TFM_*` and `UC_T` tables, we should not switch to using `cset_cn` or `pset_pn` columns.

**Comment by olejandro** [comment]
@siddharth-krishna with the latest changes both Demo 1 & 2 should be back at 100%. :-) One can't see this on CI, because pyright is throwing some errors...

For the other Demos, there seems to be an error due to renaming of `allregions` to `value`. Later on we use `melt`, but it fails because a column named `value` is already present (due to alias normalisation).

**Comment by siddharth-krishna** [comment]
Thanks Olex! I can look into the issue with `melt`.

Btw it looks like your last [commit](https://github.com/etsap-TIMES/times-excel-reader/pull/135/commits/820ef835b88fd1c053a31c877ac3306892a2c95b) has made changes to every line in the two files. Perhaps your editor's settings have changed / need to be changed to not convert line endings to Windows style?

**Comment by siddharth-krishna** [comment]
Also, I'm curious why the transform `apply_postnormalisation_fixes` that you added is reverting some of the normalization? For instance, it renames `commname` to `commodity` for `~FI_COMM` tables, but that is the opposite of the normalization specified by `veda-tags.json` for this table tag. Perhaps a better solution is to change the code to use `commname` instead of `commodity`? (Or change the canonical name for this column to `commodity` in `veda-tags.json`)

**Comment by siddharth-krishna** [comment]
Sorry for the string of comments :)

So the issue with the `melt` is that we have tables containing both an `allregions` column and a region name column e.g. `REG1` in `DemoS_004/SysSettings.xlsx:B6:H14`. How should we handle the case when a row has values in both columns? The rightmost column has priority?

**Comment by olejandro** [comment]
> Thanks Olex! I can look into the issue with `melt`.
> 
> Btw it looks like your last [commit](https://github.com/etsap-TIMES/times-excel-reader/pull/135/commits/820ef835b88fd1c053a31c877ac3306892a2c95b) has made changes to every line in the two files. Perhaps your editor's settings have changed / need to be changed to not convert line endings to Windows style?

Apologies for this! An issue with pyright was preventing me from committing, so I uploaded the files via web interface... Otherwise, I believe, my git settings handle this.

**Comment by olejandro** [comment]
> Also, I'm curious why the transform `apply_postnormalisation_fixes` that you added is reverting some of the normalization? For instance, it renames `commname` to `commodity` for `~FI_COMM` tables, but that is the opposite of the normalization specified by `veda-tags.json` for this table tag. Perhaps a better solution is to change the code to use `commname` instead of `commodity`? (Or change the canonical name for this column to `commodity` in `veda-tags.json`)

Yeah... As you can see the canonical field names are not consistent across the tables and they come from elsewhere (that is why I didn't change `veda-tag.json`). At the same time there is no reason to keep the distinction in the code (makes things confusing, I think). 

So basically, normalisation ensures canonical field names are used in the tables, while the fixes transform (we could give it a better name) allows to make the field names consistent across the tables.

I'm open to changing this approach. :-)

**Comment by olejandro** [comment]
> Sorry for the string of comments :)
> 
> So the issue with the `melt` is that we have tables containing both an `allregions` column and a region name column e.g. `REG1` in `DemoS_004/SysSettings.xlsx:B6:H14`. How should we handle the case when a row has values in both columns? The rightmost column has priority?

No problem! I think we should just do it as before, i.e. the columns to the right become rows that are lower than those to the left. I've added more renaming to the post-normalisation transform to make it work as before, so we can check whether anything else was affected by the normalisation.

**Comment by olejandro** [comment]
Seems only Demo 9 is failing now, but the convergence on e.g. Ireland has decreased.

**Comment by olejandro** [comment]
@siddharth-krishna with the latest commit all the benchmarks will execute (if pyright let's them).
I've stumbled upon another issue that is reducing the match. Somehow `TechName` (column headear) ends-up in the attribute column, while the actual name of the process is placed in the `value` column (i.e. search for "techname" in `merged_tables` to see what I mean).

**Comment by siddharth-krishna** [comment]
I fixed all regressions! :)

>  An issue with pyright was preventing me from committing

Btw, you can `git commit --no-verify` to skip the pre-commit checks.

> Yeah... As you can see the canonical field names are not consistent across the tables and they come from elsewhere (that is why I didn't change veda-tag.json). At the same time there is no reason to keep the distinction in the code (makes things confusing, I think).

I agree that it's nicer if the code uses `commodity` everywhere. But is there any reason that the `veda-tags.json` file needs to be consistent with its source? I would rather specify the canonical field name in the config file than have a hacky post-normalization fix transform.

If we do this, we can also change the canonical name for `allregions` to be `allregions` and not `value`, that would allow us to maintain the code as it is.

**Comment by olejandro** [comment]
Great, thanks! Regarding the canonical names, I guess the main reason for me was the fact that the source determines them, not us... I'd say the fixes transform is temporary and is meant to make things work while clearly showing "inconsistencies" from the source. 

There is some more info that I would like to pick up from the file. We could restructure it after that in a way that allows us to get rid of the fixes. Would that work?

**Comment by siddharth-krishna** [comment]
Okay, sounds good, thanks. If the source is something we'd like to sync with again in the future we can move the fixes code to `utils/` and make a little script that generates our version of the canonical file in `configs/`. That way it's clear that the file in `configs/` is our version that our code is consistent with, and we have a script to re-generate it from source if necessary.

**Review by olejandro — APPROVED** [review]

**Pull request merged**
