### PR TITLE
Ensure original repo is no longer ahead

### PR DESCRIPTION
**Pull request by olejandro**

### CODE REVIEW

**Review by siddharth-krishna — APPROVED** [review]

**Comment by siddharth-krishna** [comment]
Perhaps it's sufficient if we merge #128 ? This looks like it will change the readme to one line

**Comment by olejandro** [comment]
hmm... doesn't seem to be working. Still indicates a conflict and won't let me resolve it.

**Comment by siddharth-krishna** [comment]
I think the problem is the "squash and merge" strategy -- this takes all the logical changes in a PR and creates a new commit out of it. But in the case of #128 that is the empty commit:
image

If what you want to achieve is to get rid of the "1 commit behind" part of this notice:
image
then what we need to do is "merge" `microsoft:main` into `etsap-TIMES:main`. We can temporarily allow PRs being added to main as merge commits if we want to do this.

But is there some reason why we want to do this? I think right now the history clearly reflects what happened to the repository: we forked off of `microsoft:main` at some point, and all the commits are on this fork since then, except for one commit that updates `microsoft:main/README` to point to this fork. Is there some downside to the current status?

**Comment by olejandro** [comment]
> what we need to do is "merge" microsoft:main into etsap-TIMES:main. 

How would you resolve the conflict? Because if you are able to resolve the conflict by rejecting the changes from `microsoft:main` it should not matter whether it is a "squash and merge" commit or not.

The reason for wanting to get rid of "1 commit behind" is to give the right impression without the need to check out the microsoft repository. 🤷‍♂️

**Comment by siddharth-krishna** [comment]
Like I said, we need to create a merge commit in the main branch. This is a special type of commit in git that has two parents. That way GitHub can automatically determine that all commits in Microsoft main are also present in our main branch

**Pull request merged**
