### PR TITLE
Lowercase column headers

### PR DESCRIPTION
**Pull request by olejandro**
This PR lowercases all column headers. The changes contribute to #81 and will enable using of #39

### CODE REVIEW

**Comment by olejandro** [comment]
@siddharth-krishna, the idea this one is to use lowercase for column headears, but stick to uppercase for column values. Initially I was thinking to uppercase everything, but I find it easier to seperate table dimensions from values this way.

**Comment by olejandro** [comment]
Please feel free to make any improvement directly. I am happy I've managed to get it to pass the tests! 😆

**Review by siddharth-krishna — APPROVED** [review]
Thanks Olex, this look good! I pushed some minor changes.

I'm wondering what is the best place to document coding conventions like this "column names lowercase, column values uppercase" etc?

**Comment by olejandro** [comment]
Thanks Sid, good point! Let's open an issue. :-)

**Pull request merged**
