### PR TITLE
Add information on Veda tags (incl. valid fields and their aliases)

### PR DESCRIPTION
**Pull request by olejandro**
This pull requests adds an overview of Veda tags

### CODE REVIEW

**Comment by olejandro** [comment]
@samwebster @siddharth-krishna could you please take a look and share your thoughts on the structure and content of the file proposed in this draft PR?

**Comment by siddharth-krishna** [comment]
Thanks, Olex, this will be super useful!

I'm wondering if it might be helpful to have a schema for this kind of "meta-information" json file? See e.g. https://json-schema.org/learn/getting-started-step-by-step.html

And this might be overkill, but in another project I've seen people use the Dhall language to write such configuration files. The advantages are that it's a proper programming language, so you can use it to generate repetitive or programmable parts of the config automatically. More importantly, it's well typed, so it catches lots of common errors early. Let me know what you think.
https://docs.dhall-lang.org/tutorials/Getting-started_Generate-JSON-or-YAML.html

**Comment by olejandro** [comment]
#49 includes missing tags in datatypes

**Comment by olejandro** [comment]
@siddharth-krishna where should we be reading json files like the one included here (read in `transforms.py`)? Should we do it in `main.py`?

**Comment by siddharth-krishna** [comment]
Yes, perhaps `main.py` is the place for this. And perhaps we can read all such meta files (`times_mapping.txt`, `times-info.json`, this one, etc) at the beginning of the program and store the information in some sort of `TimesContext` or something like what we talked about in #11 ? This context can be passed around to each transform.

I'm also wondering if we should put all meta files in a directory of their own to avoid cluttering the root directory.

**Comment by olejandro** [comment]
Would be really great! Any chance you could propose how this can be done? E.g. using `times-info.json`, since it is already in `main`?

**Comment by siddharth-krishna** [comment]
Sure thing, I can work on this next!

**Comment by olejandro** [comment]
🙏 Thanks! this will allow us to remove a lot of dictionaries from `transforms.py`

**Review by siddharth-krishna — APPROVED** [review]
Thanks, this looks good. Just wanted to check you intended to change this branch such that the only change it now introduces is to add `veda_tags_info` to `Config` class, but this is never used anywhere? (It's fine if the usage will be a follow up PR, I just wanted to check it didn't get lost by accident)

**Comment by olejandro** [comment]
Thanks @siddharth-krishna. Yes, this is a small one. :-)

**Pull request merged**
